### ISSUE TITLE
Method that returns a boolean value

### ISSUE THREAD

**Issue by K-Sato1995** [franckverrot/clamav-client#10]
When you use `ClamAV::Commands::ScanCommand.new`, it returns an array of objects like the example in README.md.

```ruby
client.execute(ClamAV::Commands::ScanCommand.new('/tmp/path/foo.c'))
# => [#<ClamAV::SuccessResponse:0x007fbf314b9478 @file="/tmp/foo.c">]
```

I think it'd be nice to have another method that simply returns whether the virus was found in the given file.

```ruby
# returns `true` if no virus was found in the given file and returns `false` if it detected any virus.
client.safe?('/tmp/path/foo.c') #=> true
```

If you think this is a good implementation, I would love to work on this issue.
What's your view on this ???

**Comment by K-Sato1995** [comment]
My bad!! Somebody was already working on this.
 
https://github.com/franckverrot/clamav-client/pull/9/files#diff-da540a214fe8a2958a95bd4047f4d790R157

Hope it would be merged soon!!

**Comment by franckverrot** [comment]
Hey there, thanks for creating this issue.

Seems reasonable to me.  We'd need to cover edge cases like missing file, or passing a path to a directory, but it seems definitely like something that could be useful to people who don't want to subclass the client (which I do when I use this gem.)

Thanks again, don't hesitate to ask questions along the way.  I just dockerized the project so your PR will be in there https://circleci.com/gh/franckverrot/clamav-client
