### ISSUE TITLE
How complete is this interface?

### ISSUE THREAD

**Issue by deepak07** [franckverrot/clamav-client#7]
I am planning to use clamav for scanning uploaded files and was planning to create a ruby wrapper for clamav command line utilities. On searching I found your gem. 
So I just wanted to know is this production ready setup. I wanted to use this badly on my production servers.

**Comment by franckverrot** [comment]
Hi there!

I guess it all depends on your use case but I've been using it in production (along with other people) and it's working perfectly fine.

The architecture around `Command`s is great as you can build custom ones, and also: this gem doesn't use shared globals (like config setup using `MyGem.some_variable = xxx`) you could see in other gems...

Feel free to ping here if you have any questions!
